services:
  - type: web
    name: csvanalysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    routes:
      - src: /static/(.*)
        dest: /static/$1